services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./.my-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=greenlight
volumes:
  my-db:
